### PR TITLE
Add common-config repo as subtree

### PR DESCRIPTION
**Pull request by xanjohns**
### The following files were added:
[CODE_OF_CONDUCT.md](https://github.com/symbiflow/symbiflow-common-config/blob/main/CODE_OF_CONDUCT.md)
[LICENSE](https://github.com/symbiflow/symbiflow-common-config/blob/main/LICENSE)
[CONTRIBUTING.md](https://github.com/symbiflow/symbiflow-common-config/blob/main/CONTRIBUTING.md)
#### a '*' indicates the file already exists and a backup was created at /third_party/common-config/orig

### CODE REVIEW

**Review by nelsobe — APPROVED** [review]

**Review by nelsobe — CHANGES_REQUESTED** [review]
The repo already has a COPYING file.  This PR added a LICENSE file.  My understanding is that not both should exist.   Need to decide what to do in this case so the update script does the right thing.

**Comment by nelsobe** [comment]
@acomodi @kgugala 
This PR is the first PR that shows symbiflow-common-config being applied to a real repo.  In this case, the set of changes that were made to this repo are listed above in the PR text - it copied 3 files that previously were not there into the repo: CODE_OF_CONDUCT.md, LICENSE, CONTRIBUTING.md. 

As I review it I have a question: this repo uses the file COPYING to hold its license information.  But, symbiflow-common-config uses LICENSE for this purpose.  Is there a standard way of doing it? I remember being told when I set up the repo that either way is acceptable.  If so, should the update script that created this PR have removed the COPYING file and replaced it with its LICENSE file?

Also the PR fails the DCO checks.   Commit 2293fe7 is shown as failing with an x.  But, I see that that commit was signed off.  Can you clarify why it is failing?  Is it the other two that aren't signed off?

**Comment by acomodi** [comment]
Hi @nelsobe @xanjohns 

> As I review it I have a question: this repo uses the file COPYING to hold its license information. But, symbiflow-common-config uses LICENSE for this purpose. Is there a standard way of doing it? I remember being told when I set up the repo that either way is acceptable. If so, should the update script that created this PR have removed the COPYING file and replaced it with its LICENSE file?

I believe that, in case a license file is present, being it named COPYING, LICENSE or any other, we should keep it as is and do not add a new one. 

> Also the PR fails the DCO checks. Commit 2293fe7 is shown as failing with an x. But, I see that that commit was signed off. Can you clarify why it is failing? Is it the other two that aren't signed off?

It is actually failing because *all* the commits need to be signed off. I believe that the two un-signed commits have been generated by the script. I guess that  there is an option in the script used to create those commits to add the sign off.
On a side note, it would be good to have this script pushed somewhere, possibly in symbiflow-common-config as well, so that  the process can be easily reproduced.

**Comment by nelsobe** [comment]
@acomodi Thanks for the clarification - I remembered being told that the license could be held in either LICENSE or COPYING and so figured it should not replace a COPYING with a LICENSE file but wanted confirmation.

Question: what should the script do if a file already exists called LICENSE (or COPYING in this case)?  Currently, the script  checks to see if the contents that are already there match what is in common-config.  If so, it does nothing.  But, if the file exists but has different contents it replaces it.   This was done so that if the script is re-run but with new file contents it would replace the ones it previously put into the repo.  It does this with all files is copies over (CODE_OF_CONDUCT.md, LICENSE, and CONTRIBUTING.md in this case).  But, I believe in some cases this is not what we want.  Curious what your thoughts are.

Finally, yes, @xanjohns and I had talked about add the script to prjxray-common-config since we will want to re-run it at times (like when a new repo is created).  He will do so.

**Pull request closed without merging**
